// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/user.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/LoginModal.tsx";
import * as $$1 from "./islands/RegisterModal.tsx";
import * as $$2 from "./islands/SidebarTweetButton.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/user.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/LoginModal.tsx": $$0,
    "./islands/RegisterModal.tsx": $$1,
    "./islands/SidebarTweetButton.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
