// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/api/auth/login.ts";
import * as $4 from "./routes/api/auth/logout.ts";
import * as $5 from "./routes/api/auth/register.ts";
import * as $6 from "./routes/api/echo.ts";
import * as $7 from "./routes/api/users/all.ts";
import * as $8 from "./routes/api/users/id/[id].ts";
import * as $9 from "./routes/api/users/me.ts";
import * as $10 from "./routes/index.tsx";
import * as $$0 from "./islands/FollowBar.tsx";
import * as $$1 from "./islands/LoginModal.tsx";
import * as $$2 from "./islands/RegisterModal.tsx";
import * as $$3 from "./islands/Sidebar.tsx";
import * as $$4 from "./islands/SidebarTweetButton.tsx";
import * as $$5 from "./islands/Toast.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/api/auth/login.ts": $3,
    "./routes/api/auth/logout.ts": $4,
    "./routes/api/auth/register.ts": $5,
    "./routes/api/echo.ts": $6,
    "./routes/api/users/all.ts": $7,
    "./routes/api/users/id/[id].ts": $8,
    "./routes/api/users/me.ts": $9,
    "./routes/index.tsx": $10,
  },
  islands: {
    "./islands/FollowBar.tsx": $$0,
    "./islands/LoginModal.tsx": $$1,
    "./islands/RegisterModal.tsx": $$2,
    "./islands/Sidebar.tsx": $$3,
    "./islands/SidebarTweetButton.tsx": $$4,
    "./islands/Toast.tsx": $$5,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
